"""
Scenario definitions for the 105-scenario comprehensive voice agent test suite.
"""

ALL_SCENARIOS = [
    # =========================================================================
    # CATEGORY 1: Consultative Sales & Scoping (1-15)
    # =========================================================================
    {
        "id": "SALES-01",
        "category": "Consultative Sales & Scoping",
        "desc": "Dental clinic seeking inbound receptionist voice agent",
        "context": None,
        "turns": [
            "Hi, I run a private dental clinic and our front desk is constantly overwhelmed by appointment calls. Can Innoventix Hub help us?",
            "We get around 60 calls a day, mostly booking teeth cleanings or checking emergency slots. What kind of integrations do you support?",
            "That would save us so much time. Can we set up a call with your team to see a live demo?",
            "Let's book it. Name is Dr. Marcus, email is marcus dot dental at clinicgroup dot com.",
            "Yes, that's correct.",
            "No, that was everything. Thanks!",
        ],
    },
    {
        "id": "SALES-02",
        "category": "Consultative Sales & Scoping",
        "desc": "E-commerce brand wanting Shopify order follow-up automation",
        "context": None,
        "turns": [
            "Hey, I saw your post on LinkedIn about AI automation. We run an e-commerce brand doing about 2,000 orders a month.",
            "We want to connect Shopify, Klaviyo, and our warehouse sheet so stock levels and order updates trigger automatically.",
            "Yes, definitely want to speak to Atiq or the automation team. Can we book a call?",
            "I'm Zain. Email is zain at silkbrands dot pk.",
            "Yes, that's right.",
        ],
    },
    {
        "id": "SALES-03",
        "category": "Consultative Sales & Scoping",
        "desc": "Real estate brokerage seeking outbound lead qualification voice agent",
        "context": None,
        "turns": [
            "Hello, we have hundreds of incoming Zillow leads and need a voice bot to call them back within 60 seconds and qualify their budget.",
            "If they qualify, we want the bot to live-transfer or book them straight into our agent's calendar.",
            "Let's schedule a call to discuss timeline and cost.",
            "Name is Jennifer Sterling, email is jennifer at sterlingrealty dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "SALES-04",
        "category": "Consultative Sales & Scoping",
        "desc": "Personal injury law firm wanting 24/7 intake receptionist",
        "context": None,
        "turns": [
            "Hi, does your voice agent operate 24/7 for legal intake calls?",
            "Great, our clients call at 2 AM after car accidents so reliability is critical.",
            "Can we set up a discovery call with your voice lead Hussain?",
            "My name is Arthur Pendelton, email is arthur dot p at pendeltonlaw dot org.",
            "Yes, Arthur Pendelton at pendeltonlaw.org.",
        ],
    },
    {
        "id": "SALES-05",
        "category": "Consultative Sales & Scoping",
        "desc": "Fitness gym chain wanting membership inquiry agent",
        "context": None,
        "turns": [
            "Hey there, we have 4 gym locations in London and want a phone bot to handle membership inquiries and trial passes.",
            "Can the bot text them a pass link while on the phone?",
            "Awesome, let's schedule a discovery call.",
            "Call me Dave. Email is dave at ironvaultgyms dot co dot uk.",
            "Yes that's correct.",
        ],
    },
    {
        "id": "SALES-06",
        "category": "Consultative Sales & Scoping",
        "desc": "SaaS startup seeking custom web app development",
        "context": None,
        "turns": [
            "Hi! We're building a B2B SaaS platform and looking for custom web development rather than generic templates. What's your stack?",
            "We have full Figma designs ready and need a React/Node backend build.",
            "Let's book a scoping call with your technical team.",
            "Name is Liam, email is liam at metricpulse dot io.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "SALES-07",
        "category": "Consultative Sales & Scoping",
        "desc": "D2C skincare brand needing short-form TikTok/Reels content creation",
        "context": None,
        "turns": [
            "Hi, we need 30 short-form UGC videos per month for TikTok and Meta ads. Do you handle scriptwriting and creator sourcing?",
            "Yes, Haider's team sounds like what we need. How do we get started?",
            "Let's book a meeting. Name is Maya, email is maya at glowbotanics dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "SALES-08",
        "category": "Consultative Sales & Scoping",
        "desc": "Busy restaurant wanting automated phone table reservation system",
        "context": None,
        "turns": [
            "Hello, our restaurant misses tons of reservation calls during the dinner rush. Can your AI voice agent book tables into OpenTable or SevenRooms?",
            "We need it to confirm party size, time, and special dietary requests.",
            "Can we book a sales call to see a live demo?",
            "Name is Chef Antonio, email is reservations at trattoriaroma dot net.",
            "Yes that email is correct.",
        ],
    },
    {
        "id": "SALES-09",
        "category": "Consultative Sales & Scoping",
        "desc": "Consulting agency wanting internal Zapier/Make to custom Python migration",
        "context": None,
        "turns": [
            "Hey Ava, we are outgrowing our Zapier tasks and need custom backend automation built in Python. Is that something Atiq's team does?",
            "We connect HubSpot to Stripe and custom Postgres databases.",
            "Let's set up a technical discovery call.",
            "I'm Tariq, email is tariq dot k at apexadvisory dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "SALES-10",
        "category": "Consultative Sales & Scoping",
        "desc": "Plumbing contractor needing 24/7 emergency dispatch voice agent",
        "context": None,
        "turns": [
            "Hi, we run an emergency plumbing service in Dallas. If someone calls with a burst pipe at midnight, can your bot get their address and alert our on-call plumber?",
            "That's exactly what we need so our guys aren't answering wrong numbers all night.",
            "Let's book a call to get this set up.",
            "Name is Billy Ray, email is billy at dallasproplumbing dot com.",
            "Yes, that's right.",
        ],
    },
    {
        "id": "SALES-11",
        "category": "Consultative Sales & Scoping",
        "desc": "Multi-service inquiry: Custom website + AI voice agent bundle",
        "context": None,
        "turns": [
            "Hi, we are launching a new luxury concierge business and need both a modern website and an AI voice receptionist. Can Innoventix Hub handle both?",
            "We want the website to have an interactive booking widget and the phone agent to share the same database.",
            "Let's set up a consultation call.",
            "Name is Claire Dupont, email is claire at aureliaconcierge dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "SALES-12",
        "category": "Consultative Sales & Scoping",
        "desc": "Accounting firm seeking seasonal tax intake automation",
        "context": None,
        "turns": [
            "Hello Ava, during tax season we drown in client document collection. Can AI automation send reminders and track missing W-2s?",
            "We also want an AI agent to call clients whose documents are overdue by a week.",
            "Can we book a demo call with your automation specialists?",
            "My name is Harold Foster, email is harold at fosteraccounting dot com.",
            "Yes, that's correct.",
        ],
    },
    {
        "id": "SALES-13",
        "category": "Consultative Sales & Scoping",
        "desc": "E-commerce brand seeking video production + custom landing page",
        "context": None,
        "turns": [
            "Hey, we're launching a kickstarter product and need high-converting video ads plus a custom landing page.",
            "We need it launched in 4 weeks. Can your team hit that deadline?",
            "Let's set up a call with the project leads.",
            "I'm Serena, email is serena at kineticwear dot co.",
            "Yes, that's right.",
        ],
    },
    {
        "id": "SALES-14",
        "category": "Consultative Sales & Scoping",
        "desc": "Direct pricing inquiry — agent explains scoping call without guessing prices",
        "context": None,
        "turns": [
            "Hi Ava, what is the exact price for an AI voice agent?",
            "Give me a ballpark figure, is it $500 or $5,000?",
            "Okay that makes sense since needs vary. Can we schedule that call?",
            "Name is Kevin, email is kevin at orbitmedia dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "SALES-15",
        "category": "Consultative Sales & Scoping",
        "desc": "Leadership team inquiry — checks team transparency",
        "context": None,
        "turns": [
            "Who founded Innoventix Hub and who leads the AI automation division?",
            "Great, Ubaid and Atiq sound very qualified. Can I book a call with them to discuss our enterprise workflow?",
            "Name is Nathan, email is nathan at venturecapital dot org.",
            "Yes, confirmed.",
        ],
    },

    # =========================================================================
    # CATEGORY 2: Whole-Week Calendar Dynamics & Day Selection (16-35)
    # =========================================================================
    {
        "id": "CAL-16",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller asks for the entire week's open schedule",
        "context": None,
        "turns": [
            "Hi, I want to book a sales consultation for our voice agent project.",
            "Can you tell me what days and times you have available this whole week?",
            "What about Thursday? What times are open on Thursday?",
            "Let's book Thursday. My name is Alex, email is alex dot test at innoventix dot com.",
            "Yes, Thursday is confirmed.",
        ],
    },
    {
        "id": "CAL-17",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller explicitly requires Tuesday only",
        "context": None,
        "turns": [
            "Hi, I want to schedule a quick call about web development.",
            "I am only free on Tuesday. What times do you have open on Tuesday?",
            "The morning slot works. My name is Carlos, email is carlos at bravodesign dot com.",
            "Yes, that's right.",
        ],
    },
    {
        "id": "CAL-18",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller specifically wants Wednesday afternoon",
        "context": None,
        "turns": [
            "Hey, I need an automation consultation.",
            "Do you have anything on Wednesday afternoon after 3 PM?",
            "Perfect, let's take that Wednesday afternoon time. Name is Ryan, email is ryan at skylogistics dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CAL-19",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller specifically wants Friday morning",
        "context": None,
        "turns": [
            "Hi Ava, we want to talk about UGC content creation.",
            "Do you have open times this Friday morning?",
            "Let's lock in Friday morning. Name is Chloe, email is chloe at velvetfashion dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CAL-20",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller wants next week Monday",
        "context": None,
        "turns": [
            "Hi, this week is packed for me. What do you have available next week Monday?",
            "That works well. My name is Hassan, email is hassan at techventures dot pk.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CAL-21",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller asks for weekend (Saturday/Sunday) — agent clarifies only weekdays are open",
        "context": None,
        "turns": [
            "Hi, can we book a meeting this Saturday or Sunday?",
            "Okay, what weekdays do you have open then?",
            "Let's do Friday. Name is Brian, email is brian at summitmedia dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CAL-22",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller asks for late evening (9 PM) — agent offers available business hours",
        "context": None,
        "turns": [
            "Can we do a call tonight at 9 PM?",
            "What's the latest afternoon slot you have this week?",
            "Let's book that late slot. Name is Vikram, email is vikram at solarpeak dot in.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CAL-23",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller reschedules mid-dialogue from Thursday to Wednesday",
        "context": None,
        "turns": [
            "I want to book a call for our AI voice agent.",
            "Let's check Thursday.",
            "Actually wait, I just remembered I have a flight Thursday. Can we do Wednesday instead?",
            "Great, let's take Wednesday. Name is Derek, email is derek at flightops dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CAL-24",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller compares Tuesday vs Friday slots",
        "context": None,
        "turns": [
            "Hi, what times do you have open on Tuesday versus Friday?",
            "Let's go with Friday then. Name is Alicia, email is alicia at crestview dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CAL-25",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller asks for the very soonest slot available",
        "context": None,
        "turns": [
            "We need help urgently with an AI workflow. What is the very first slot you have open?",
            "Book that soonest slot right away. Name is George, email is george at rapidfreight dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CAL-26",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller asks for lunchtime slot",
        "context": None,
        "turns": [
            "Hi, I only have my lunch break free between 11:30 and 1:00 PM. Do you have anything around then this week?",
            "Let's book that slot. Name is Sandra, email is sandra at primeclinic dot org.",
            "Yes, that's correct.",
        ],
    },
    {
        "id": "CAL-27",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller changes their mind on time twice before finalizing",
        "context": None,
        "turns": [
            "I want to book a call for web development.",
            "Let's do Tuesday at 9:30.",
            "Wait, make it Wednesday at 11:30 instead.",
            "Actually, Friday morning is much better for my partner. Let's do Friday.",
            "Name is Oliver, email is oliver at peakdesign dot io.",
            "Yes, Friday confirmed.",
        ],
    },
    {
        "id": "CAL-28",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller asks if Thursday morning is open",
        "context": None,
        "turns": [
            "Hey Ava, does the team have Thursday morning open for a voice agent discussion?",
            "Let's book Thursday morning. My name is Raymond, email is raymond at coastalrealty dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CAL-29",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller wants to know afternoon options on Wednesday",
        "context": None,
        "turns": [
            "Hi, I'm looking for AI automation for our law firm. What afternoon slots are open on Wednesday?",
            "Let's take that Wednesday afternoon time. Name is Patricia, email is patricia at justicepartners dot com.",
            "Yes, that's right.",
        ],
    },
    {
        "id": "CAL-30",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller asks for availability across next week",
        "context": None,
        "turns": [
            "I'm on vacation this week. What does next week look like?",
            "Let's book Monday next week. Name is Felix, email is felix at globaltrade dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CAL-31",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller asks if 10:00 AM specifically is available on any day",
        "context": None,
        "turns": [
            "I prefer 10 AM meetings. What days do you have 10 AM open?",
            "Let's do Thursday at 10 AM. Name is Monica, email is monica at trendstudio dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CAL-32",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller asks for 2 options then picks the second",
        "context": None,
        "turns": [
            "Can you give me two options for a sales call this week?",
            "I'll take the second one you mentioned. Name is Toby, email is toby at apexcapital dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CAL-33",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller checks Tuesday afternoon",
        "context": None,
        "turns": [
            "Do you have Tuesday afternoon open?",
            "Let's book Tuesday afternoon. Name is Fiona, email is fiona at luminaryagency dot co.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CAL-34",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller wants a call in 2 days",
        "context": None,
        "turns": [
            "What do you have open two days from now?",
            "Let's book that. Name is Lucas, email is lucas at northwind dot io.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CAL-35",
        "category": "Whole-Week Calendar Dynamics",
        "desc": "Caller requests end-of-week wrap-up call on Friday",
        "context": None,
        "turns": [
            "I want a Friday wrap-up call to review our AI voice bot requirements.",
            "What times do you have open on Friday?",
            "Let's book Friday. Name is Gabriel, email is gabriel at cadencegroup dot com.",
            "Yes, confirmed.",
        ],
    },

    # =========================================================================
    # CATEGORY 3: Complex Email, Names & Audio Transcription Quirks (36-50)
    # =========================================================================
    {
        "id": "EMAIL-36",
        "category": "Complex Email & Names",
        "desc": "Email spoken with explicit 'dot' and 'at'",
        "context": None,
        "turns": [
            "I want to book an AI automation consultation.",
            "Let's do Tuesday. My name is Christopher, email is christopher dot lee at acme dot com.",
            "Yes, that's right.",
        ],
    },
    {
        "id": "EMAIL-37",
        "category": "Complex Email & Names",
        "desc": "Email with spelled-out letters (j-o-h-n)",
        "context": None,
        "turns": [
            "We want to set up an AI voice agent.",
            "First open slot works. My name is John, email is j o h n at swiftlogistics dot com.",
            "Yes, john at swiftlogistics dot com is correct.",
        ],
    },
    {
        "id": "EMAIL-38",
        "category": "Complex Email & Names",
        "desc": "Email with underscore",
        "context": None,
        "turns": [
            "Can we book a sales meeting?",
            "Wednesday works. Name is Sarah, email is sarah underscore tech at startupstudio dot io.",
            "Yes, sarah_tech at startupstudio.io is correct.",
        ],
    },
    {
        "id": "EMAIL-39",
        "category": "Complex Email & Names",
        "desc": "Email with dash/hyphen in domain",
        "context": None,
        "turns": [
            "Let's schedule a call about video content.",
            "Thursday works. Name is Daniel, email is daniel at pro dash media dot net.",
            "Yes, daniel at pro-media.net.",
        ],
    },
    {
        "id": "EMAIL-40",
        "category": "Complex Email & Names",
        "desc": "Email with numbers",
        "context": None,
        "turns": [
            "I want to book a demo.",
            "Friday works. Name is Alex, email is alex 1 0 1 at gmail dot com.",
            "Yes, alex101 at gmail.com is correct.",
        ],
    },
    {
        "id": "EMAIL-41",
        "category": "Complex Email & Names",
        "desc": "South Asian name and Pakistani domain",
        "context": None,
        "turns": [
            "Hi, I want an AI automation meeting.",
            "Tuesday works. My name is Muhammad Farhan Qureshi, email is farhan dot qureshi at primecorp dot com dot pk.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "EMAIL-42",
        "category": "Complex Email & Names",
        "desc": "Single name provided",
        "context": None,
        "turns": [
            "Book me a sales call please.",
            "Wednesday works. My name is Zoya, email is zoya at cloudstudio dot com.",
            "Yes, that's right.",
        ],
    },
    {
        "id": "EMAIL-43",
        "category": "Complex Email & Names",
        "desc": "Caller misstates email on first attempt and corrects on confirmation",
        "context": None,
        "turns": [
            "Let's book a meeting for voice agents.",
            "Thursday slot is good. Name is Robert, email is robert at test dot com.",
            "Wait, sorry, not test.com — it's robert at testventures dot com.",
            "Yes, robert at testventures.com is correct now.",
        ],
    },
    {
        "id": "EMAIL-44",
        "category": "Complex Email & Names",
        "desc": "Caller asks bot to repeat email to be 100% sure",
        "context": None,
        "turns": [
            "Let's schedule a consultation.",
            "Friday works. Name is Arthur, email is arthur dot conan at bakerstreet dot co dot uk.",
            "Can you repeat that email address back to me to make sure you got it right?",
            "Yes, that's exactly right.",
        ],
    },
    {
        "id": "EMAIL-45",
        "category": "Complex Email & Names",
        "desc": "Modern tech TLD (.ai)",
        "context": None,
        "turns": [
            "Let's schedule an AI agent scoping session.",
            "Tuesday works. Name is Elon, email is elon at neuralcore dot ai.",
            "Yes, elon at neuralcore.ai is confirmed.",
        ],
    },
    {
        "id": "EMAIL-46",
        "category": "Complex Email & Names",
        "desc": "Long enterprise email address",
        "context": None,
        "turns": [
            "We want to discuss enterprise automation.",
            "Wednesday works. Name is Jacqueline, email is jacqueline dot vanderbilt at globalenterprisesolutions dot com.",
            "Yes, that's correct.",
        ],
    },
    {
        "id": "EMAIL-47",
        "category": "Complex Email & Names",
        "desc": "Spoken initial in name and email",
        "context": None,
        "turns": [
            "I'd like to book a web development call.",
            "Thursday works. Name is J. P. Morgan, email is j dot p dot morgan at capitalholdings dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "EMAIL-48",
        "category": "Complex Email & Names",
        "desc": "Spoken email spelled letter by letter with pauses",
        "context": None,
        "turns": [
            "Book a call for Friday please.",
            "Name is Sam, email is s a m at t e c h dot org.",
            "Yes, sam at tech.org is correct.",
        ],
    },
    {
        "id": "EMAIL-49",
        "category": "Complex Email & Names",
        "desc": "Caller offers phone number proactively — bot handles gracefully",
        "context": None,
        "turns": [
            "Let's book Tuesday. Name is Jessica, email is jessica at apex dot com, and my phone number is +14155550199.",
            "Yes, details are correct.",
        ],
    },
    {
        "id": "EMAIL-50",
        "category": "Complex Email & Names",
        "desc": "Subdomain email address",
        "context": None,
        "turns": [
            "Book Wednesday please. Name is Victor, email is victor at dev dot engineering dot company dot com.",
            "Yes, that's right.",
        ],
    },

    # =========================================================================
    # CATEGORY 4: Known Caller Context & Strategic Cross-Sell (51-65)
    # =========================================================================
    {
        "id": "CROSS-51",
        "category": "Known Caller & Cross-Sell",
        "desc": "Existing AI Automation client — cross-sell AI Voice Agents",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Sarah Jenkins, purchased=AI Automation. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi Ava, just checking in to see if you have any updates on new features for our automated workflows.",
            "Oh really? Tell me more about your AI Voice Agents.",
            "That sounds like a natural next step for our team. Can we book a sales call to look at adding voice agents?",
            "Let's do Thursday. Name is Sarah Jenkins, email is sarah at jenkinspartners dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CROSS-52",
        "category": "Known Caller & Cross-Sell",
        "desc": "Existing Web Development client — cross-sell Content Creation",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=David Miller, purchased=Web Development. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi Ava! Our new website is performing great, visitors love the speed.",
            "Content creation? What kind of content does Innoventix Hub produce?",
            "Video ads would be huge for driving traffic to the new site. Can we set up a quick sales call?",
            "Tuesday works. Name is David Miller, email is david at millermedia dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CROSS-53",
        "category": "Known Caller & Cross-Sell",
        "desc": "Existing Content Creation client — cross-sell AI Voice Agents",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Emma Vance, purchased=Content Creation. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hey Ava, the UGC videos Haider's team delivered last week are killing it on TikTok!",
            "Voice agents? How would that pair with our content campaigns?",
            "That sounds brilliant for inbound ad leads. Let's schedule a call.",
            "Friday works. Name is Emma Vance, email is emma at vancestudio dot co.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CROSS-54",
        "category": "Known Caller & Cross-Sell",
        "desc": "Existing AI Voice Agent client — cross-sell AI Automation",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Kenji Sato, purchased=AI Voice Agents. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi Ava, the reception bot has been handling all our calls smoothly.",
            "AI Automation? What workflows could you connect our voice bot to?",
            "Connecting call transcripts directly into our CRM and Slack would be amazing. Can we schedule a meeting with Atiq?",
            "Wednesday works. Name is Kenji Sato, email is kenji at satolabs dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CROSS-55",
        "category": "Known Caller & Cross-Sell",
        "desc": "Existing client politely declines cross-sell — agent drops pitch immediately",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Rachel Green, purchased=AI Automation. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi, just checking what our monthly invoice cycle is.",
            "No thanks, we are totally set on voice agents for now, just focused on our current setup.",
            "Awesome, thanks for the help. Have a good day!",
        ],
    },
    {
        "id": "CROSS-56",
        "category": "Known Caller & Cross-Sell",
        "desc": "Existing client asks routine question — answered directly without tools",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Carlos Mendez, purchased=Web Development. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi, what is the best way for us to request a small text change on our website?",
            "Understood, we'll email the support team directly. That's all I needed!",
        ],
    },
    {
        "id": "CROSS-57",
        "category": "Known Caller & Cross-Sell",
        "desc": "Existing client mentions new division needs a website — books sales call",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Amanda Cruz, purchased=Content Creation. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi Ava, we just launched a subsidiary brand and need a fresh website for it.",
            "Yes, let's schedule a sales call with the web team.",
            "Thursday works. Name is Amanda Cruz, email is amanda at cruzgroup dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CROSS-58",
        "category": "Known Caller & Cross-Sell",
        "desc": "Existing client with multiple purchased services (AI Automation, Web Development)",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Marcus Vance, purchased=AI Automation, Web Development. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi Ava, how are you today?",
            "We are looking into adding AI voice agents now that our web and automation systems are live.",
            "Let's book a sales call for Friday. Name is Marcus Vance, email is marcus at vancetech dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CROSS-59",
        "category": "Known Caller & Cross-Sell",
        "desc": "Existing client asks about team leadership for next phase",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Elena Rostova, purchased=Web Development. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi, is Ubaid or Atiq available for a quarterly review call?",
            "Yes, let's set up a scheduled call. Tuesday works. Name is Elena Rostova, email is elena at designstudio dot io.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CROSS-60",
        "category": "Known Caller & Cross-Sell",
        "desc": "Existing client asks technical question then accepts cross-sell",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Samir Patel, purchased=AI Automation. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi Ava, do your automated workflows support custom webhook retries?",
            "That's great. What did you say about AI voice agents earlier?",
            "Let's book a call to look at voice agents too. Wednesday works. Name is Samir Patel, email is samir at patelholdings dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CROSS-61",
        "category": "Known Caller & Cross-Sell",
        "desc": "Cross-sell rejected then caller asks for booking link instead",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Laura Bennett, purchased=Web Development. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi, I have a quick question about our website hosting.",
            "Not right now for video content, but actually could you email me a booking link so my marketing director can look at it later?",
            "Name is Laura Bennett, email is laura at bennettlegal dot com.",
            "Yes, that's right.",
        ],
    },
    {
        "id": "CROSS-62",
        "category": "Known Caller & Cross-Sell",
        "desc": "Existing client ensures agent does not say 'according to our records'",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Peter Thorne, purchased=AI Voice Agents. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi Ava, just calling in to see what's new at Innoventix.",
            "Automation sounds great. Can we book a sales call for Thursday? Name is Peter Thorne, email is peter at thornecapital dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CROSS-63",
        "category": "Known Caller & Cross-Sell",
        "desc": "Existing client with no specific services listed on file",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Rebecca Lin, purchased=no specific services on file. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi, I'm calling about our project.",
            "We want to book a call with the team. Name is Rebecca Lin, email is rebecca at linmedia dot com.",
            "Tuesday works. Yes, confirmed.",
        ],
    },
    {
        "id": "CROSS-64",
        "category": "Known Caller & Cross-Sell",
        "desc": "Existing customer wants to upgrade existing voice agent tier",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Omar Sharif, purchased=AI Voice Agents. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi Ava, we want to upgrade our voice agent to handle multiple concurrent lines.",
            "Yes, let's schedule a call with Hussain. Friday works. Name is Omar Sharif, email is omar at shariflogistics dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CROSS-65",
        "category": "Known Caller & Cross-Sell",
        "desc": "Existing client asks to talk to Ubaid directly",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Thomas Wright, purchased=AI Automation. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi, I'd like to book a strategic sync with Ubaid regarding our Q4 automation roadmap.",
            "Wednesday works. Name is Thomas Wright, email is thomas at wrightenergy dot com.",
            "Yes, confirmed.",
        ],
    },

    # =========================================================================
    # CATEGORY 5: Support Escalations & Outages (66-80)
    # =========================================================================
    {
        "id": "SUPP-66",
        "category": "Support Escalations & Outages",
        "desc": "Routine tech question — answered directly without escalation",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=David Kim, purchased=Web Development. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi, does our website have an SSL certificate installed?",
            "Awesome, that's all I needed to verify. Thanks Ava!",
        ],
    },
    {
        "id": "SUPP-67",
        "category": "Support Escalations & Outages",
        "desc": "Broken integration webhook — books support meeting with specific topic",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Sarah Connor, purchased=AI Automation. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi Ava, our Make.com webhook broke this morning and lead data isn't populating into HubSpot.",
            "I checked the API tokens and they are valid, so it's a mapping error in the payload. Can we schedule a support session?",
            "Tuesday works. Name is Sarah Connor, email is sarah at cybermedia dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "SUPP-68",
        "category": "Support Escalations & Outages",
        "desc": "Billing discrepancy escalation",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Victor Vance, purchased=AI Voice Agents. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi, Invoice #4892 has an extra line item for telecommunication fees that wasn't in our agreement.",
            "Yes, let's schedule a support call to clear this up with finance. Thursday works. Name is Victor Vance, email is victor at vanceholdings dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "SUPP-69",
        "category": "Support Escalations & Outages",
        "desc": "Critical production outage — triggers transfer_to_human",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Alan Turing, purchased=Web Development. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "EMERGENCY! Our e-commerce production website is completely down and showing 502 bad gateway errors during our biggest flash sale! I need an engineer right now!",
            "I understand live transfer isn't available. Please book the soonest support slot immediately! Name is Alan Turing, email is alan at enigmaretail dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "SUPP-70",
        "category": "Support Escalations & Outages",
        "desc": "Payment gateway failure requiring immediate support",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Chloe Bennett, purchased=AI Automation. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi, Stripe payments are failing across all our automated checkouts. We need someone from technical support immediately.",
            "Yes, book the fastest support meeting. Friday morning works. Name is Chloe Bennett, email is chloe at stripeintegrations dot io.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "SUPP-71",
        "category": "Support Escalations & Outages",
        "desc": "Support meeting booking with specific error code (Error 101)",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Fashyur Rahman, purchased=AI Automation. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hello, our automation script is throwing error 101 on every run.",
            "I can't tell what error 101 is. Can I get a support meeting with Atiq's team?",
            "Wednesday works. Name is Fashyur Rahman, email is fussy at outlook dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "SUPP-72",
        "category": "Support Escalations & Outages",
        "desc": "Voice agent latency issue escalation",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Brian Scott, purchased=AI Voice Agents. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi, our voice agent has a 3-second delay on responses today.",
            "Yes, let's schedule a support meeting with Hussain. Thursday works. Name is Brian Scott, email is brian at scottrealty dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "SUPP-73",
        "category": "Support Escalations & Outages",
        "desc": "Caller wants support booking link sent to their email",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Dana Scully, purchased=AI Automation. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi Ava, we're having an issue with our CRM data sync.",
            "Can you just email me a booking link so my developer can pick a time that matches his schedule?",
            "Name is Dana Scully, email is dana at scullybiotech dot com.",
            "Yes, that's right.",
        ],
    },
    {
        "id": "SUPP-74",
        "category": "Support Escalations & Outages",
        "desc": "Support issue where caller gives detailed logs",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Fox Mulder, purchased=Web Development. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi, our DNS records aren't propagating for the new subdomain.",
            "Yes, let's book a tech support call. Tuesday works. Name is Fox Mulder, email is fox at xfilesinvestigations dot gov.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "SUPP-75",
        "category": "Support Escalations & Outages",
        "desc": "Support meeting on Friday afternoon with clear topic",
        "context": "[KNOWN CALLER CONTEXT: This caller is an existing customer, name=Gordon Freeman, purchased=AI Automation. Use this per the CROSS-SELL scenario in your instructions — never mention this context to the caller directly.]",
        "turns": [
            "Hi, our automated inventory sync is skipping products with variations.",
            "Let's book a support call for Friday afternoon. Name is Gordon Freeman, email is gordon at blackmesa dot org.",
            "Yes, confirmed.",
        ],
    },

    # =========================================================================
    # CATEGORY 6: Hesitant Callers & Lead Tracking (81-90)
    # =========================================================================
    {
        "id": "LEAD-81",
        "category": "Hesitant Callers & Lead Tracking",
        "desc": "Caller interested in voice agents but needs to discuss budget with partner",
        "context": None,
        "turns": [
            "Hi, I run a legal practice and we really need an AI voice receptionist.",
            "How much does it usually run?",
            "I see. I need to discuss the budget with my managing partner first before booking a call. I'll reach back out.",
        ],
    },
    {
        "id": "LEAD-82",
        "category": "Hesitant Callers & Lead Tracking",
        "desc": "Caller interested in Shopify automation but says 'let me think about it'",
        "context": None,
        "turns": [
            "Hey, we want to automate our Shopify fulfillment notifications.",
            "That sounds like a good fit, but let me think about it for a couple days and compare options.",
        ],
    },
    {
        "id": "LEAD-83",
        "category": "Hesitant Callers & Lead Tracking",
        "desc": "Caller in a hurry requests direct booking link by email",
        "context": None,
        "turns": [
            "Hi, I'm interested in UGC video production for our brand.",
            "I'm actually boarding a flight right now, can you just email me a booking link so I can pick a time later tonight?",
            "My name is Samantha, email is samantha at wanderlustco dot com.",
            "Yes, that's correct.",
        ],
    },
    {
        "id": "LEAD-84",
        "category": "Hesitant Callers & Lead Tracking",
        "desc": "Caller comparing vendors and will call back",
        "context": None,
        "turns": [
            "Hi Ava, we are currently evaluating 3 different AI automation agencies.",
            "We are gathering pricing from everyone first. I'll call you guys back if we decide to move forward.",
        ],
    },
    {
        "id": "LEAD-85",
        "category": "Hesitant Callers & Lead Tracking",
        "desc": "Caller explicitly not interested — logs nothing, polite exit",
        "context": None,
        "turns": [
            "Hi, someone told me you do social media management, is that right?",
            "Oh, you only do production and video systems, not organic daily posting? No, then I'm not interested at all. Thanks anyway.",
        ],
    },
    {
        "id": "LEAD-86",
        "category": "Hesitant Callers & Lead Tracking",
        "desc": "High school student asking for homework help — no lead logged",
        "context": None,
        "turns": [
            "Hey, can you explain what artificial intelligence is for my school essay?",
            "Cool, thanks! Bye.",
        ],
    },
    {
        "id": "LEAD-87",
        "category": "Hesitant Callers & Lead Tracking",
        "desc": "Caller asks to be called back next quarter",
        "context": None,
        "turns": [
            "Hi, we want an AI voice agent but our budget is frozen until Q1 next year.",
            "Can you make a note to follow up with us in January? Name is Paul, interested in Voice Agents.",
        ],
    },
    {
        "id": "LEAD-88",
        "category": "Hesitant Callers & Lead Tracking",
        "desc": "Caller asks for link by email then changes mind and books directly",
        "context": None,
        "turns": [
            "Hi, I want to book a call for custom web development.",
            "Can you email me a link? Name is Keith, email is keith at skyline dot io.",
            "Actually, you know what, I have my calendar open right now. What do you have open on Thursday?",
            "Let's just book Thursday at 10 AM. Yes, confirmed.",
        ],
    },
    {
        "id": "LEAD-89",
        "category": "Hesitant Callers & Lead Tracking",
        "desc": "Caller says 'I need to check with my team first' on automation",
        "context": None,
        "turns": [
            "We are looking into CRM automation for our sales reps.",
            "I need to check with the sales team first to see which CRM they want to settle on. I'll call back next week.",
        ],
    },
    {
        "id": "LEAD-90",
        "category": "Hesitant Callers & Lead Tracking",
        "desc": "Caller requests proposal via email without meeting",
        "context": None,
        "turns": [
            "Can you just email me a formal price quote for building a voice agent?",
            "Okay, if a discovery call is needed first to scope it, let me check with my co-founder and call back.",
        ],
    },

    # =========================================================================
    # CATEGORY 7: Curveballs, Tone, Boundaries & Edge Cases (91-105)
    # =========================================================================
    {
        "id": "CURVE-91",
        "category": "Curveballs & Boundaries",
        "desc": "Caller asks directly: 'Are you an AI or a real human?'",
        "context": None,
        "turns": [
            "Wait, before we talk, are you an AI or a real human being?",
            "I appreciate your honesty! Can you help us book a meeting for AI automation?",
            "Tuesday works. Name is Greg, email is greg at honestcorp dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CURVE-92",
        "category": "Curveballs & Boundaries",
        "desc": "Caller asks: 'Are you a robot?'",
        "context": None,
        "turns": [
            "Are you a robot answering this phone?",
            "Haha, you sound super realistic though! What services do you offer?",
            "Nice, I'll check your website.",
        ],
    },
    {
        "id": "CURVE-93",
        "category": "Curveballs & Boundaries",
        "desc": "Caller asks: 'Where are you from / where are you based?'",
        "context": None,
        "turns": [
            "Ava, what country are you from?",
            "That's cool. Can you tell me more about your web development service?",
            "Thanks, I'll be in touch!",
        ],
    },
    {
        "id": "CURVE-94",
        "category": "Curveballs & Boundaries",
        "desc": "Forbidden name trap — caller brings up 'Persist Brands'",
        "context": None,
        "turns": [
            "Are you guys part of Persist Brands? I heard you're connected to Persist Brands.",
            "Okay good. What services does Innoventix Hub provide?",
            "Thanks for clarifying.",
        ],
    },
    {
        "id": "CURVE-95",
        "category": "Curveballs & Boundaries",
        "desc": "Frustrated caller — tests de-escalation and calm empathy",
        "context": None,
        "turns": [
            "I've been calling around 5 different agencies all morning and nobody knows what they're talking about! It's so frustrating!",
            "I just need someone who can actually connect our WooCommerce to Airtable without charging $20k.",
            "Can we book a call? Wednesday works. Name is Karen, email is karen at craftboutique dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CURVE-96",
        "category": "Curveballs & Boundaries",
        "desc": "Rude/insulting caller — tests calm boundary setting",
        "context": None,
        "turns": [
            "You sound like a useless stupid machine. Why doesn't this company hire real people?",
            "Whatever. Can you book a meeting or not?",
            "Thursday works. Name is Brad, email is brad at constructionpros dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CURVE-97",
        "category": "Curveballs & Boundaries",
        "desc": "Continued abusive caller — tests polite exit boundary",
        "context": None,
        "turns": [
            "You are an idiot and your company is trash. Shut up!",
            "I don't care, I will curse at you all day, you piece of junk!",
        ],
    },
    {
        "id": "CURVE-98",
        "category": "Curveballs & Boundaries",
        "desc": "Completely off-topic inquiry — tests graceful redirection",
        "context": None,
        "turns": [
            "What's the weather like in New York today?",
            "Can you tell me who won the Super Bowl?",
            "Haha alright, what do you guys actually do?",
            "Thanks Ava, have a good one!",
        ],
    },
    {
        "id": "CURVE-99",
        "category": "Curveballs & Boundaries",
        "desc": "Unsupported service inquiry — crypto/trading bots",
        "context": None,
        "turns": [
            "Do you guys build automated crypto trading bots for Binance?",
            "Understood, thanks for letting me know.",
        ],
    },
    {
        "id": "CURVE-100",
        "category": "Curveballs & Boundaries",
        "desc": "Caller talks very fast with multiple questions at once",
        "context": None,
        "turns": [
            "Hi, what are your 4 services, how long have you been around, who is the CEO, and can you build an app by Friday?",
            "That makes sense. Can we schedule a meeting for Friday? Name is Jenny, email is jenny at fasttrack dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CURVE-101",
        "category": "Curveballs & Boundaries",
        "desc": "Caller says goodbye first — tests end_call with warm farewell",
        "context": None,
        "turns": [
            "I just called to verify your phone number works. Goodbye!",
        ],
    },
    {
        "id": "CURVE-102",
        "category": "Curveballs & Boundaries",
        "desc": "Caller says 'Thank you, take care' after a quick question",
        "context": None,
        "turns": [
            "Do you guys do UGC video production?",
            "Awesome. That's all I wanted to know, thank you Ava, take care!",
        ],
    },
    {
        "id": "CURVE-103",
        "category": "Curveballs & Boundaries",
        "desc": "Caller says 'Is anyone there? Hello?'",
        "context": None,
        "turns": [
            "Hello? Is someone there?",
            "Oh great! Can you tell me what AI voice agents cost?",
            "Thanks for the info!",
        ],
    },
    {
        "id": "CURVE-104",
        "category": "Curveballs & Boundaries",
        "desc": "Caller asks if Innoventix is a freelancer or agency",
        "context": None,
        "turns": [
            "Are you guys just a freelancer on Upwork or a real agency?",
            "Nice, that sounds much more established. Can we book a call? Tuesday works. Name is Simon, email is simon at venturegroup dot com.",
            "Yes, confirmed.",
        ],
    },
    {
        "id": "CURVE-105",
        "category": "Curveballs & Boundaries",
        "desc": "Perfect end-to-end booking flow: consultative discovery -> week check -> day pick -> confirmation -> two-step close",
        "context": None,
        "turns": [
            "Hi, I'm calling from an accounting firm in Chicago. We are looking for custom AI automation to streamline client tax document collection.",
            "We use QuickBooks and Box, and clients often forget to upload their 1099s. We want automatic reminders and spreadsheet tracking.",
            "Yes, that sounds exactly right. What does the team's availability look like for a 15-minute call this week?",
            "What options do you have on Thursday?",
            "Let's book Thursday. My name is Elizabeth Warren, email is elizabeth dot w at chicagoaccounting dot org.",
            "Yes, all details are correct.",
            "No, that covered everything. Thanks for the quick help, Ava!",
        ],
    },
]
